# Generated by Django 4.1.1 on 2022-09-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='kaina',
            field=models.FloatField(verbose_name='Kaina'),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='kiekis',
            field=models.IntegerField(verbose_name='Kiekis'),
        ),
    ]
